### BƯỚC 1: Đăng nhập để lấy Token (Role Admin)
POST http://localhost:5249/api/auth/login
Content-Type: application/json

{
    "username": "adminn",
    "password": "123"
}

### BƯỚC 2: Test API Công khai (Bất kỳ ai có Token đều xem được)
GET http://localhost:5249/api/data/common-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWlubiIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzc4NTk1NDEzLCJleHAiOjE3Nzg1OTkwMTMsImlhdCI6MTc3ODU5NTQxM30.IxkJwI7HjpqKYVzlDWIF7FfqtuL35zhhpqJ-L9rSCxU

### BƯỚC 3: Test API Bảo mật (Chỉ Admin mới xem được)
GET http://localhost:5249/api/data/admin-only-secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWlubiIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzc4NTk1NDEzLCJleHAiOjE3Nzg1OTkwMTMsImlhdCI6MTc3ODU5NTQxM30.IxkJwI7HjpqKYVzlDWIF7FfqtuL35zhhpqJ-L9rSCxU